/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as PlayRouteImport } from './routes/play'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as PlayCategorySortRouteImport } from './routes/play.category-sort'
import { Route as PlayFamilyFacesRouteImport } from './routes/play.family-faces'
import { Route as PlayMemoryMatchRouteImport } from './routes/play.memory-match'
import { Route as PlaySequenceRouteImport } from './routes/play.sequence'
import { Route as PlayWhatsMissingRouteImport } from './routes/play.whats-missing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCategorySortRoute = PlayCategorySortRouteImport.update({
  id: '/category-sort',
  path: '/category-sort',
  getParentRoute: () => PlayRoute,
} as any)
const PlayFamilyFacesRoute = PlayFamilyFacesRouteImport.update({
  id: '/family-faces',
  path: '/family-faces',
  getParentRoute: () => PlayRoute,
} as any)
const PlayMemoryMatchRoute = PlayMemoryMatchRouteImport.update({
  id: '/memory-match',
  path: '/memory-match',
  getParentRoute: () => PlayRoute,
} as any)
const PlaySequenceRoute = PlaySequenceRouteImport.update({
  id: '/sequence',
  path: '/sequence',
  getParentRoute: () => PlayRoute,
} as any)
const PlayWhatsMissingRoute = PlayWhatsMissingRouteImport.update({
  id: '/whats-missing',
  path: '/whats-missing',
  getParentRoute: () => PlayRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/family': typeof FamilyRoute
  '/play': typeof PlayRouteWithChildren
  '/staff': typeof StaffRoute
  '/play/category-sort': typeof PlayCategorySortRoute
  '/play/family-faces': typeof PlayFamilyFacesRoute
  '/play/memory-match': typeof PlayMemoryMatchRoute
  '/play/sequence': typeof PlaySequenceRoute
  '/play/whats-missing': typeof PlayWhatsMissingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/family': typeof FamilyRoute
  '/play': typeof PlayRouteWithChildren
  '/staff': typeof StaffRoute
  '/play/category-sort': typeof PlayCategorySortRoute
  '/play/family-faces': typeof PlayFamilyFacesRoute
  '/play/memory-match': typeof PlayMemoryMatchRoute
  '/play/sequence': typeof PlaySequenceRoute
  '/play/whats-missing': typeof PlayWhatsMissingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/family': typeof FamilyRoute
  '/play': typeof PlayRouteWithChildren
  '/staff': typeof StaffRoute
  '/play/category-sort': typeof PlayCategorySortRoute
  '/play/family-faces': typeof PlayFamilyFacesRoute
  '/play/memory-match': typeof PlayMemoryMatchRoute
  '/play/sequence': typeof PlaySequenceRoute
  '/play/whats-missing': typeof PlayWhatsMissingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/family'
    | '/play'
    | '/staff'
    | '/play/category-sort'
    | '/play/family-faces'
    | '/play/memory-match'
    | '/play/sequence'
    | '/play/whats-missing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/family'
    | '/play'
    | '/staff'
    | '/play/category-sort'
    | '/play/family-faces'
    | '/play/memory-match'
    | '/play/sequence'
    | '/play/whats-missing'
  id:
    | '__root__'
    | '/'
    | '/family'
    | '/play'
    | '/staff'
    | '/play/category-sort'
    | '/play/family-faces'
    | '/play/memory-match'
    | '/play/sequence'
    | '/play/whats-missing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamilyRoute: typeof FamilyRoute
  PlayRoute: typeof PlayRouteWithChildren
  StaffRoute: typeof StaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/category-sort': {
      id: '/play/category-sort'
      path: '/category-sort'
      fullPath: '/play/category-sort'
      preLoaderRoute: typeof PlayCategorySortRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/family-faces': {
      id: '/play/family-faces'
      path: '/family-faces'
      fullPath: '/play/family-faces'
      preLoaderRoute: typeof PlayFamilyFacesRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/memory-match': {
      id: '/play/memory-match'
      path: '/memory-match'
      fullPath: '/play/memory-match'
      preLoaderRoute: typeof PlayMemoryMatchRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/sequence': {
      id: '/play/sequence'
      path: '/sequence'
      fullPath: '/play/sequence'
      preLoaderRoute: typeof PlaySequenceRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/whats-missing': {
      id: '/play/whats-missing'
      path: '/whats-missing'
      fullPath: '/play/whats-missing'
      preLoaderRoute: typeof PlayWhatsMissingRouteImport
      parentRoute: typeof PlayRoute
    }
  }
}

interface PlayRouteChildren {
  PlayCategorySortRoute: typeof PlayCategorySortRoute
  PlayFamilyFacesRoute: typeof PlayFamilyFacesRoute
  PlayMemoryMatchRoute: typeof PlayMemoryMatchRoute
  PlaySequenceRoute: typeof PlaySequenceRoute
  PlayWhatsMissingRoute: typeof PlayWhatsMissingRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayCategorySortRoute: PlayCategorySortRoute,
  PlayFamilyFacesRoute: PlayFamilyFacesRoute,
  PlayMemoryMatchRoute: PlayMemoryMatchRoute,
  PlaySequenceRoute: PlaySequenceRoute,
  PlayWhatsMissingRoute: PlayWhatsMissingRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamilyRoute: FamilyRoute,
  PlayRoute: PlayRouteWithChildren,
  StaffRoute: StaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
